name = input("Введите Ваше имя: ")
print(name, type(name))
print('Здравствуйте,', name)
current_year = 2024
year = input('В каком году Вы родились? ')
age = current_year - int(year)
print("Вы этом году Вам", age, 'лет')
print("Строка В Нижнем Регистре")
print("Строка В Нижнем Регистре".upper())
print("Строка В Нижнем Регистре".lower())
print("Строка В Нижнем Регистре".replace("Нижнем","Верхнем"))
print("Строка В Нижнем Регистре".replace(" ",""))

user_input = input('Введите координаты цели: ')
print(user_input, type(user_input))
x, y = map(int, input('Введите координаты: ').split())
print(x, type(x))
print(y, type(y))
car_model = 'Москвич 412 Из Железа'
print(car_model)
print(car_model.find('о'), car_model.rfind('о'))
print(car_model.replace('о', 'аа'))
print(car_model.upper())
print(car_model.replace('о', 'аа').upper())
print(car_model.lower())
print(car_model.replace('о', 'аа').lower())
car_model = car_model.replace(' ', '')
print(car_model, car_model.isalpha())
new_car_model = car_model.replace('412', 'красный')
print(new_car_model, new_car_model.isalpha())
print(car_model, car_model.isnumeric())
new_car_model = car_model.replace('Москвич', '')
new_car_model = new_car_model.replace('ИзЖелеза', '')
print(new_car_model, new_car_model.isnumeric())
